// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package _model

import (
	"database/sql"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash []byte
	Name         string
	CreatedAt    sql.NullTime
	AvatarUrl    sql.NullString
}
