// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package _model

import (
	"database/sql"
	"time"
)

type User struct {
	ID           int64
	Email        string
	PasswordHash []byte
	Name         string
	CreatedAt    time.Time
	AvatarUrl    sql.NullString
}
